# Generated by Django 3.1.4 on 2020-12-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_tweets_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='follow',
        ),
    ]
