# Generated by Django 3.1.4 on 2020-12-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
