# Generated by Django 3.1.4 on 2020-12-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0004_auto_20201208_0450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
