# Generated by Django 3.1.4 on 2020-12-11 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='follow',
            field=models.ManyToManyField(related_name='_twitteruser_follow_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
