# Generated by Django 3.1.4 on 2020-12-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0006_twitteruser_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='name',
        ),
    ]
